// Generated by CoffeeScript 1.4.0
(function() {
  var ContextBuilder, TestEnv,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContextBuilder = require('./context_builder');

  module.exports = TestEnv = (function(_super) {

    __extends(TestEnv, _super);

    function TestEnv() {
      return TestEnv.__super__.constructor.apply(this, arguments);
    }

    TestEnv.prototype.activateAssertion = function() {
      return this.addHelper(require('assert'));
    };

    TestEnv.prototype.build = function(done) {
      var _this = this;
      return TestEnv.__super__.build.call(this, function(err) {
        _this.activateAssertion();
        return done(err);
      });
    };

    return TestEnv;

  })(ContextBuilder);

}).call(this);
