// Generated by CoffeeScript 1.4.0
(function() {
  var ContextBuilder, TestRunner,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContextBuilder = require('./context_builder');

  module.exports = TestRunner = (function(_super) {

    __extends(TestRunner, _super);

    function TestRunner() {
      return TestRunner.__super__.constructor.apply(this, arguments);
    }

    TestRunner.prototype.activateAssertion = function() {
      return this.addHelper(require('assert'));
    };

    TestRunner.prototype.activateMocha = function() {
      return this.addHelper({
        it: global.it,
        before: global.before,
        describe: global.describe
      });
    };

    TestRunner.prototype.build = function(done) {
      var _this = this;
      return TestRunner.__super__.build.call(this, function(err) {
        _this.activateAssertion();
        _this.activateMocha();
        return done(err);
      });
    };

    return TestRunner;

  })(ContextBuilder);

}).call(this);
